### ISSUE TITLE
Census Variables

### ISSUE THREAD

**Issue by MicheleTobias** [datalab-dev/graves-endocrine_surgeons#7]
We need a list of census variables to chose from.

**Comment by alisonsnwong** [comment]
I believe the `geography` column shows the smallest geography at which a given variable is available. Since the block level is smaller than the tract level, the tract data is also available for the income (or any other variable that shows `block group` in its geography column. Here's an article I found about it: https://walker-data.com/tidycensus/articles/basic-usage.html

**Comment by MicheleTobias** [comment]
@alisonsnwong so it sounds like the code you're working on already deals with this then?

**Comment by alisonsnwong** [comment]
> @alisonsnwong so it sounds like the code you're working on already deals with this then?

Yeah. I think most of the variables we found should work as long as we specify `geography = 'tract'` in the argument when using get_acs().

**Comment by MicheleTobias** [comment]
Fantastic teamwork! These are important questions to ask and make sure we've addressed, and I'm glad to hear we've got this covered already.
